### ISSUE TITLE
Trying to run pyepm EtherEx.yaml but getting HTTPConnectionPool(host='127.0.0.1', port=8545): Max retries exceeded with url: /

### ISSUE THREAD

**Issue by tomachinz** [etherex/etherex#22]
I am starting my private node using the following geth command:

geth --datadir ~/Library/Ethereum/devnet --ipcpath  ~/Library/Ethereum/geth.ipc --mine --etherbase 0x82Ac50716A13B7f08F9cAb371418E08bEFa5D096 --nodiscover --maxpeers 0 --rpc --rpcapi "db,eth,net,web3"  --rpccorsdomain "*" --port "30303" --pprofport 6060 --rpcport "8080" --nat "any" --identity "TCorp-PRIVATE-CHAIN" --minerthreads 1 --verbosity 4 --pprof  --shh  --unlock 0x82Ac50716A13B7f08F9cAb371418E08bEFa5D096

then I am planning to deploy your wondering contracts..... no idea really what Im upto but....

13inch:contracts tom$ pyepm EtherEx.yaml
=====
PyEPM 1.0.2
=====

Deploying EtherEx.yaml...

set:
  Replacing $caktux with 0x884b9f474007cfffeb80b8622de4ed22ece6df93 (3)
  Replacing $zg with 0x239eb5afa5b1da814a3ccb60e79de1f933f1b470 (3)
  Replacing $mids with 0x2ad9e5d8960882c07b96e2a21d5a39ab082e7368 (3)

deploy:
  Deploying etherex.se...
Traceback (most recent call last):
  File "/usr/local/bin/pyepm", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/pyepm/pyepm.py", line 105, in main
    deployment.deploy()
  File "/Library/Python/2.7/site-packages/pyepm/deploy.py", line 83, in deploy
    contract_names=contract_names if contract_names else name)
  File "/Library/Python/2.7/site-packages/pyepm/deploy.py", line 176, in create
    tx_hashes = self.try_create_deploy(contract, from_, gas, gas_price, value, retry, skip, wait, verbose, contract_names)
  File "/Library/Python/2.7/site-packages/pyepm/deploy.py", line 256, in try_create_deploy
    tx_hash = self.try_create(contract, contract_name=contract_names, from_=from_, gas=gas, gas_price=gas_price, value=value)
  File "/Library/Python/2.7/site-packages/pyepm/deploy.py", line 264, in try_create
    tx_hash = instance.create(contract, from_=from_, gas=gas, gas_price=gas_price, endowment=value)
  File "/Library/Python/2.7/site-packages/pyepm/api.py", line 207, in create
    net_price = self.gasprice()
  File "/Library/Python/2.7/site-packages/pyepm/api.py", line 144, in gasprice
    result = self._rpc_post('eth_gasPrice', None)
  File "/Library/Python/2.7/site-packages/pyepm/api.py", line 84, in _rpc_post
    r = requests.post(self.jsonrpc_url, data=json.dumps(payload), headers=headers)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10df1f310>: Failed to establish a new connection: [Errno 61] Connection refused',))
13inch:contracts tom$

**Comment by nomiAA** [comment]
https://stackoverflow.com/questions/24045265/python-requests-httpconnectionpool-and-max-retries-exceeded-with-url

```
import socket
socket.create_connection(('127.0.0.1', 8545), timeout=2)
```
