### ISSUE TITLE
pyepm.api.ApiException: code=-32000, message="unknown account"

### ISSUE THREAD

**Issue by tomachinz** [etherex/etherex#24]
Heya!
Sorry to bother you dudes, I sure hope you can help me get past this show stopper that's had me stuck for a couple of months and I've basically given up fixing it.... I'm trying to bring up your Etherex exchange instance on my Mac 10.10.5. Want to make a NZD-Ethereum exchange for down-under!

I need help solving the error: pyepm.api.ApiException: code=-32000, message="unknown account"

Any ideas where I can set or check the account settings?

==
I'm starting up my private-net like this:
==
nice geth --datadir ~/Library/Ethereum/devnet --ipcpath  ~/Library/Ethereum/geth.ipc --mine --etherbase 0x82Ac50716A13B7f08F9cAb371418E08bEFa5D096 --nodiscover --maxpeers 0 --rpc --rpcapi "db,eth,net,web3"  --rpccorsdomain http://localhost:8089 --port="30303" --pprofport="6060" --rpcport="8545" --nat "any" --minerthreads 1 --verbosity 3 --pprof  --shh   --unlock 0x82Ac50716A13B7f08F9cAb371418E08bEFa5D096

==
I then startup etherex, so far so good:
==

13inch:frontend tom$ grunt
Running "webpack-dev-server:start" (webpack-dev-server) task
webpack-dev-server on port 8089
Version: webpack 1.14.0
                                 Asset     Size  Chunks             Chunk Names
7ea52b1914022c4ebc15dafe3b116d03.woff2  30.5 kB          [emitted]
  f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]
  e18bbf611f2a2e43afc071aa2f4e1512.ttf  45.4 kB          [emitted]
  89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]
  303a14e0add7b3b94327f9f349cf0b4a.jpg  11.1 kB          [emitted]
  072d782a9ddd24fd16f50d5b5a6b5481.eot    35 kB          [emitted]
 03d14078bd4d8d2525df26928e72f900.woff  38.2 kB          [emitted]
4868942007735e9bf8096dbd51ab4c83.woff2  30.4 kB          [emitted]
  fb319a9750a64a4888f3d2805e7ad6b0.ttf  76.4 kB          [emitted]
  69c898bcb60d75bfd2518780428ee8eb.svg   206 kB          [emitted]
  1f18335a6cc3bde61c116370c7b0b788.eot  35.3 kB          [emitted]
 ff09f0600f30ccc2789d51d03d794a06.woff  38.4 kB          [emitted]
 fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB          [emitted]
  1721a5c97ce23ab97e3ad0c90bd4f4b5.ttf  76.4 kB          [emitted]
  8ff2f359d1286c170d1f1fc356e998e9.svg   207 kB          [emitted]
  7a697e6d4548decd889c8d6bb4164be4.eot  37.9 kB          [emitted]
 2abf6bb3a6f60451054c2a7ac338cd93.woff  41.1 kB          [emitted]
3cc2079e69ac976ffe92418179449475.woff2  32.8 kB          [emitted]
  a933c16a2acbad281147577027220125.ttf  82.5 kB          [emitted]
  226f0cfee2031c8dd863a648379aacd9.svg   211 kB          [emitted]
  304888470673edcc9a9f95062e33ddd2.eot  8.18 kB          [emitted]
  3438f55fd9930f13e3bd34ee2dc299fb.ttf  8.02 kB          [emitted]
  36da4d49be8f55e660f9e81269824128.svg  7.96 kB          [emitted]
                                app.js  6.29 MB       0  [emitted]  main
webpack: bundle is now VALID.

=====
Then I try to deploy contracts:
=====

13inch:contracts tom$ pyepm EtherEx.yaml
PyEPM 1.0.2
=====

Deploying EtherEx.yaml...

set:
  Replacing $caktux with 0x884b9f474007cfffeb80b8622de4ed22ece6df93 (3)
  Replacing $zg with 0x239eb5afa5b1da814a3ccb60e79de1f933f1b470 (3)
  Replacing $mids with 0x2ad9e5d8960882c07b96e2a21d5a39ab082e7368 (3)

deploy:
  Deploying etherex.se...
    Gas price: 0.0200 szabo * 1.0000
    Our price: 20,000,000,000
Traceback (most recent call last):
  File "/usr/local/bin/pyepm", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/pyepm/pyepm.py", line 105, in main
    deployment.deploy()
  File "/Library/Python/2.7/site-packages/pyepm/deploy.py", line 83, in deploy
    contract_names=contract_names if contract_names else name)
  File "/Library/Python/2.7/site-packages/pyepm/deploy.py", line 176, in create
    tx_hashes = self.try_create_deploy(contract, from_, gas, gas_price, value, retry, skip, wait, verbose, contract_names)
  File "/Library/Python/2.7/site-packages/pyepm/deploy.py", line 256, in try_create_deploy
    tx_hash = self.try_create(contract, contract_name=contract_names, from_=from_, gas=gas, gas_price=gas_price, value=value)
  File "/Library/Python/2.7/site-packages/pyepm/deploy.py", line 264, in try_create
    tx_hash = instance.create(contract, from_=from_, gas=gas, gas_price=gas_price, endowment=value)
  File "/Library/Python/2.7/site-packages/pyepm/api.py", line 222, in create
    return self._rpc_post('eth_sendTransaction', params)
  File "/Library/Python/2.7/site-packages/pyepm/api.py", line 93, in _rpc_post
    raise ApiException(response['error']['code'], response['error']['message'])
pyepm.api.ApiException: code=-32000, message="unknown account"
13inch:contracts tom$

Do I need to deploy contracts everytime I start and stop my private-net? Thanks!

==
Some details:
==
Darwin 13inch.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Apr 11 16:12:42 PDT 2017; root:xnu-2782.50.9.2.3~1/RELEASE_X86_64 x86_64
node -v v7.8.0
npm -v 4.2.0
eth -v
dyld: Symbol not found: __ZN8CryptoPP10RandomPool34GenerateIntoBufferedTransformationERNS_22BufferedTransformationERKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEy
  Referenced from: /usr/local/Cellar/cpp-ethereum/1.3.0/lib/libdevcrypto.dylib
  Expected in: /usr/local/opt/cryptopp/lib/libcryptopp.dylib
 in /usr/local/Cellar/cpp-ethereum/1.3.0/lib/libdevcrypto.dylib
Trace/BPT trap: 5
Python 2.7.10
eth --version
dyld: Symbol not found: __ZN8CryptoPP10RandomPool34GenerateIntoBufferedTransformationERNS_22BufferedTransformationERKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEy
  Referenced from: /usr/local/Cellar/cpp-ethereum/1.3.0/lib/libdevcrypto.dylib
  Expected in: /usr/local/opt/cryptopp/lib/libcryptopp.dylib
 in /usr/local/Cellar/cpp-ethereum/1.3.0/lib/libdevcrypto.dylib
Trace/BPT trap: 5
13inch:contracts tom$
 eth --version
dyld: Symbol not found: __ZN8CryptoPP10RandomPool34GenerateIntoBufferedTransformationERNS_22BufferedTransformationERKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEy
  Referenced from: /usr/local/Cellar/cpp-ethereum/1.3.0/lib/libdevcrypto.dylib
  Expected in: /usr/local/opt/cryptopp/lib/libcryptopp.dylib
 in /usr/local/Cellar/cpp-ethereum/1.3.0/lib/libdevcrypto.dylib
Trace/BPT trap: 5

**Comment by waitoff** [comment]
pyepm EtherEx.yaml -a 0x012345 (your unlocked account with eth >0)

thnx @abvhiael  (https://github.com/abvhiael/etherex#deployment)
